version: "3.9"
services:
  auth-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      DB_NAME: "auth_db"
      ALGORITHM: "HS256"
      SECRET_KEY: "secret"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ping: 1})' | mongo localhost:27017"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mongo_data:
